---
argo_customize_num_users: "{{ num_users | default(3) }}"
argo_customize_gitea_namespace: gitea
argo_customize_argo_namespace: openshift-gitops
argo_customize_gitea_admin_user: gitea
argo_customize_gitea_user_name_base: user
argo_customize_gitea_user_password: "{{ common_password }}"
argo_customize_argo_user_name_base: user
argo_customize_argo_user_password: "{{ common_password }}"