---
gitea_customize_gitea_namespace: gitea
gitea_customize_gitea_admin_user: gitea
gitea_customize_gitea_admin_password: AVo2zmNf34KptdHe
gitea_customize_gitea_public_repos:
- name: customers-app
  url: https://github.com/mthirion/lb1153-customers-app.git
  per_user: false
  private: false
- name: customers-gitops
  url: https://github.com/mthirion/lb1153-customers-gitops.git
  per_user: true
  private: false
- name: pipeline-gitops
  url: https://github.com/treddy08/lb1153-pipeline-gitops.git
  per_user: true
  private: false
- name: env-gitops
  url: https://github.com/mthirion/lb1153-env-gitops.git
  per_user: true
  private: false
- name: leaderboard-gitops
  url: https://github.com/mthirion/lb1153-leaderboard-gitops.git
  per_user: false
  private: true
gitea_customize_gitea_num_users: "{{ num_users | default(3) }}"
gitea_customize_gitea_user_name_base: user
gitea_customize_gitea_user_password: MTg5OTIy
gitea_customize_student_name: "{{ student_name | default('lab-user') }}"